archives:
  - format: zip
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  extra_files:
    - glob: .empty
      name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS.sig"
